spring:
#  profiles:
#    active: dev
  application:
    name: corn-springboot-study

server:
  servlet:
    context-path: /corn
  port: 8000

imooc:
  springboot:
    version: 2.1,2.1.4
    name: study

management:
  endpoint:
    shutdown:
      enabled: true # 最特殊的监控端点
  endpoints:
    web:
      exposure:
        include: "*" # 打开所有的监控点

# /imooc/actuator/info

info:
  app:
    name: corn-springboot-study
    groupId: com.corn.springboot.study
    version: 1.0-SNAPSHOT
